@startuml class_diagram_models
skinparam DefaultFontName "Times New Roman"
skinparam DefaultFontSize 14

user --|> Model
setting --|> Model
category --|> Model
product --|> Model
product_option --|> Model
cart --|> Model
Model <|-- cart_item
Model <|-- product_follow
Model <|-- cost
Model <|-- order
Model <|-- order_item
Model <|-- payment

abstract class Model<<T>> {
    +id: int
    +created_at: datetime
    +updated_at: datetime

    +save(): T
    +destroy(): void
    +findOne(id: int): T
    +findAll(options: QueryOption): Array<T>
    +update(t: T, options?: QueryOption): Model
    +create(t: T, options?: QueryOption): Model
    +delete(id: int): void
    +findAndCountAll(options: QueryOption): Array<T>
}

object QueryOption {
    +where: object
    +limit: int
    +offset: int
    +order: string
}

class setting {
  +key: string
  +value: JSON
}

class category {
  +name: string
  +description: string
  +link: string
  +image_url: string
}

class product {
  +name: string
  +detail: string
  +category_id: int
  +stock: int
  +status: string
}

class product_option {
  +name: string
  +type: string
  +product_id: int
}

class cart {
  +user_id: int
}

class cart_item {
  +cart_id: int
  +quantity: int
  +product_id: int
  +product_option_id: int
}

class product_follow {
  +product_id: int
  +user_id: int
}

class user {
  +first_name: string
  +last_name: string
  +email: string
  +hashed_password: string
  +phone: string
  +address: string
  +role: string
  +imgUrl: string
}

class cost {
  +id:int
  +total_cost: int,
  +cost_type: string,
  +product_id: int,
  +employee_id: int,
  +description: string
}

class order {
  +user_id: int
  +status: string
  +total_amount: double
  +discount: double
  +payment_method: string
  +payment_status: string
  +info: JSON
}

class order_item {
  +order_id: int
  +quantity: int
  +product_id: int
  +product_option_id: int
}

class payment {
  +order_id: int
  +method: string
  +bank_code: string
  +status: string
  +amount: int
  +currency: string
  +description: string
  +transaction_id: string
  +transaction_info: string
  +transaction_status: string
  +transaction_time: Date
  +transaction_data: JSON
}

@enduml