@startuml class_diagram

entity setting {
  +id: INTEGER
  +key: TEXT
  +value: JSON
}

entity category {
  +id: INTEGER
  +name: TEXT
  +description: TEXT
  +link: TEXT
  +image_url: TEXT
}

entity product {
  +id: INTEGER
  +name: TEXT
  +detail: TEXT
  +category_id: INTEGER
  +stock: INTEGER
  +status: TEXT
}

entity product_option {
  +id: INTEGER
  +name: TEXT
  +type: TEXT
  +product_id: INTEGER
}

entity cart {
  +id: INTEGER
  +user_id: INTEGER
}

entity cart_item {
  +id: INTEGER
  +cart_id: INTEGER
  +quantity: INTEGER
  +product_id: INTEGER
  +product_option_id: INTEGER
}

entity product_follow {
  +id: INTEGER
  +product_id: INTEGER
  +user_id: INTEGER
}

entity user {
  +id: INTEGER
  +first_name: TEXT
  +last_name: TEXT
  +email: TEXT
  +hashed_password: TEXT
  +phone: TEXT
  +address: TEXT
  +role: TEXT
  +imgUrl: TEXT
}

entity cost {
  +id:INTEGER
  +total_cost: INTEGER,
  +cost_type: TEXT,
  +product_id: INTEGER,
  +employee_id: INTEGER,
  +description: TEXT
}

entity order {
  +id: INTEGER
  +user_id: INTEGER
  +status: TEXT
  +total_amount: double
  +discount: double
  +payment_method: TEXT
  +payment_status: TEXT
  +info: JSON
}

entity order_item {
  +id: INTEGER
  +order_id: INTEGER
  +quantity: INTEGER
  +product_id: INTEGER
  +product_option_id: INTEGER
}

entity payment {
  +id: INTEGER
  +order_id: INTEGER
  +method: TEXT
  +bank_code: TEXT
  +status: TEXT
  +amount: INTEGER
  +currency: TEXT
  +description: TEXT
  +transaction_id: TEXT
  +transaction_info: TEXT
  +transaction_status: TEXT
  +transaction_time: Date
  +transaction_data: JSON
}

' Các mối quan hệ
category "1" -- "0..*" product : contains
cart "1" -- "0..*" cart_item : contains
user "1" -- "0..*" order : places
user "1" -- "0..1" cart : owns
order "1" -- "0..*" order_item : contains
order "1" -- "0..1" payment : paid_by
product "1" -- "0..*" product_option : has
cart_item "0..*" -- "1" product : is
order_item "0..*" -- "1" product : is
cost "1" -- "0..1" product : purchasing
cost "1" -- "0..1" user : salary
product_follow "0..*" -- "1" product : is
product_follow "0..*" -- "1" user : of
@enduml