@startuml class_diagram

object settings {
  +id: INTEGER
  +key: TEXT
  +value: JSON
}

object categories {
  +id: INTEGER
  +name: TEXT
  +description: TEXT
  +link: TEXT
  +image_url: TEXT
}

object products {
  +id: INTEGER
  +name: TEXT
  +detail: TEXT
  +category_id: INTEGER
  +stock: INTEGER
  +status: TEXT
}

object product_options {
  +id: INTEGER
  +name: TEXT
  +type: TEXT
  +product_id: INTEGER
}

object carts {
  +id: INTEGER
  +user_id: INTEGER
}

object cart_items {
  +id: INTEGER
  +cart_id: INTEGER
  +quantity: INTEGER
  +product_id: INTEGER
  +product_option_id: INTEGER
}

object product_follows {
  +id: INTEGER
  +product_id: INTEGER
  +user_id: INTEGER
}

object users {
  +id: INTEGER
  +first_name: TEXT
  +last_name: TEXT
  +email: TEXT
  +hashed_password: TEXT
  +phone: TEXT
  +address: TEXT
  +role: TEXT
  +imgUrl: TEXT
}

object costs {
  +id:INTEGER
  +total_cost: INTEGER,
  +cost_type: TEXT,
  +product_id: INTEGER,
  +employee_id: INTEGER,
  +description: TEXT
}

object orders {
  +id: INTEGER
  +user_id: INTEGER
  +status: TEXT
  +total_amount: double
  +discount: double
  +payment_method: TEXT
  +payment_status: TEXT
  +info: JSON
}

object order_items {
  +id: INTEGER
  +order_id: INTEGER
  +quantity: INTEGER
  +product_id: INTEGER
  +product_option_id: INTEGER
}

object payments {
  +id: INTEGER
  +order_id: INTEGER
  +method: TEXT
  +bank_code: TEXT
  +status: TEXT
  +amount: INTEGER
  +currency: TEXT
  +description: TEXT
  +transaction_id: TEXT
  +transaction_info: TEXT
  +transaction_status: TEXT
  +transaction_time: Date
  +transaction_data: JSON
}

object tasks{
  +id: INTEGER
  +title: TEXT
  +description: TEXT
  +status: TEXT
  +assignedTo: INTEGER
  +start_date: Date
}

' Các mối quan hệ
categories "1" -- "0..*" products : contains
carts "1" -- "0..*" cart_items : contains
users "1" -- "0..*" orders : places
users "1" -- "0..1" carts : owns
orders "1" -- "0..*" order_items : contains
orders "1" -- "0..1" payments : paid_by
products "1" -- "0..*" product_options : has
cart_items "0..*" -- "1" products : is
order_items "0..*" -- "1" products : is
costs "1" -- "0..1" products : purchasing
costs "1" -- "0..1" users : salary
product_follows "0..*" -- "1" products : is
product_follows "0..*" -- "1" users : of
users "1" -- "0..*" tasks : assignedTo
@enduml