# fly.toml app configuration file generated for car-part-ecommerce on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "car-part-ecommerce"
primary_region = "sin"  # Singapore - gần Vietnam nhất

[build]
  # Fly.io sẽ tự động detect Node.js và chạy npm install
  # Không cần builder khi có Dockerfile hoặc để Fly tự detect

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"
  method = "get"
  path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Health check endpoint
[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = 2000
  tls_skip_verify = false

# Cấu hình static files (nếu cần)
[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

# Cấu hình cho multiple processes
[processes]
  web = "npm start"

# Cấu hình scaling
[scaling]
  min_machines = 0
  max_machines = 10

# Cấu hình restart policy
[restart]
  policy = "on-failure"

# Cấu hình log
[logging]
  level = "info"